development:
  adapter: postgresql
  database: foodlist_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: foodlist_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: foodlist_prod
  pool: 5
  timeout: 5000
