require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EditRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # EditRequest. As you add validations to EditRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EditRequestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all edit_requests as @edit_requests" do
      edit_request = EditRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:edit_requests).should eq([edit_request])
    end
  end

  describe "GET show" do
    it "assigns the requested edit_request as @edit_request" do
      edit_request = EditRequest.create! valid_attributes
      get :show, {:id => edit_request.to_param}, valid_session
      assigns(:edit_request).should eq(edit_request)
    end
  end

  describe "GET new" do
    it "assigns a new edit_request as @edit_request" do
      get :new, {}, valid_session
      assigns(:edit_request).should be_a_new(EditRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested edit_request as @edit_request" do
      edit_request = EditRequest.create! valid_attributes
      get :edit, {:id => edit_request.to_param}, valid_session
      assigns(:edit_request).should eq(edit_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EditRequest" do
        expect {
          post :create, {:edit_request => valid_attributes}, valid_session
        }.to change(EditRequest, :count).by(1)
      end

      it "assigns a newly created edit_request as @edit_request" do
        post :create, {:edit_request => valid_attributes}, valid_session
        assigns(:edit_request).should be_a(EditRequest)
        assigns(:edit_request).should be_persisted
      end

      it "redirects to the created edit_request" do
        post :create, {:edit_request => valid_attributes}, valid_session
        response.should redirect_to(EditRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved edit_request as @edit_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        EditRequest.any_instance.stub(:save).and_return(false)
        post :create, {:edit_request => {}}, valid_session
        assigns(:edit_request).should be_a_new(EditRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EditRequest.any_instance.stub(:save).and_return(false)
        post :create, {:edit_request => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested edit_request" do
        edit_request = EditRequest.create! valid_attributes
        # Assuming there are no other edit_requests in the database, this
        # specifies that the EditRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EditRequest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => edit_request.to_param, :edit_request => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested edit_request as @edit_request" do
        edit_request = EditRequest.create! valid_attributes
        put :update, {:id => edit_request.to_param, :edit_request => valid_attributes}, valid_session
        assigns(:edit_request).should eq(edit_request)
      end

      it "redirects to the edit_request" do
        edit_request = EditRequest.create! valid_attributes
        put :update, {:id => edit_request.to_param, :edit_request => valid_attributes}, valid_session
        response.should redirect_to(edit_request)
      end
    end

    describe "with invalid params" do
      it "assigns the edit_request as @edit_request" do
        edit_request = EditRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EditRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => edit_request.to_param, :edit_request => {}}, valid_session
        assigns(:edit_request).should eq(edit_request)
      end

      it "re-renders the 'edit' template" do
        edit_request = EditRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EditRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => edit_request.to_param, :edit_request => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested edit_request" do
      edit_request = EditRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => edit_request.to_param}, valid_session
      }.to change(EditRequest, :count).by(-1)
    end

    it "redirects to the edit_requests list" do
      edit_request = EditRequest.create! valid_attributes
      delete :destroy, {:id => edit_request.to_param}, valid_session
      response.should redirect_to(edit_requests_url)
    end
  end

end
